from . import res_company
from . import res_partner
from . import product_template
from . import res_config_setting
from . import sale_order
from . import stock_picking
from . import order_tracking
from . import sale_order_line
from . import product_brand
from . import loyalty_card
from . import stock_rule
